
notifications:
  email:
    on_success: never
    on_failure: always

# In order to ask travis to install packages:
# sudo: required AND under matrix/include:
# addons:
#   apt:
#     packages:
#       - qemu-system-x86
# [ at the same level of env ]

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      env: NO_BUSYBOX=1 RELEASE=1
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      env: NO_BUSYBOX=1 RELEASE=0 CMAKE_ARGS='-DUSE_GCOV=on'
    - os: linux
      dist: trusty
      sudo: false
      language: generic
      env: NO_BUSYBOX=1 RELEASE=0 CXX=clang++


before_install:
  - ./scripts/build_toolchain --skip-install-pkgs

install:
  - make -j
  - make -j gtests

script:
  - MALLOC_CHECK_=2 ./build/gtests
  - ./scripts/generate_coverage_report # Does nothing if not USE_GCOV.

# Just in case we want to use build on Travis with docker images:
#
# os: linux
# dist: trusty
# sudo: required
# language: generic

# before_install:
#   - docker pull vvaltchev/exos_build:ver2
#   - docker run -it -d --name exos_build vvaltchev/exos_build:ver2 bash
#   - docker exec exos_build git clone https://github.com/vvaltchev/experimentOs
#   - docker exec exos_build mv /exos_toolchain /experimentOs/toolchain

# install:
#   - docker exec exos_build make -C /experimentOs -j
#   - docker exec exos_build make -C /experimentOs -j gtests

# script:
#   - docker exec exos_build /experimentOs/build/gtests
#
#
