trigger:
  paths:
    include:
      - 'scripts/configurator/**'

jobs:
  - job: configurator
    pool:
      vmImage: 'ubuntu-24.04'
    strategy:
      matrix:
        Python310:
          python.version: '3.10'
        Python311:
          python.version: '3.11'
        Python312:
          python.version: '3.12'
        Python313:
          python.version: '3.13'

    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(python.version)'
      inputs:
        versionSpec: '$(python.version)'

    - script: python -m unittest discover scripts/configurator/parser
      displayName: 'Run unit tests'
