trigger:
  branches:
    exclude:
      - readme*
      - temp-*
      - exp-*

  paths:
    include:
      - 'scripts/build_toolchain'
      - 'scripts/tc/pkgs/**'
    exclude:
      - 'README.md'
      - '*.md'

pool:
  vmImage: 'ubuntu-22.04'


container: 'vvaltchev/debian:v4'

variables:
  CI: 1
  RUNNING_IN_CI: 1
  GTEST_SHUFFLE: 0
  ARCH: riscv64

steps:
  - script: printenv
    displayName: Dump env
  - script: sudo -E ./scripts/build_toolchain
    displayName: "Install pkgs"
  - script: sudo -E ./scripts/build_toolchain -s build_gtest
    displayName: "Build gtest"
  - script: sudo -E ./scripts/build_toolchain -s build_gmock
    displayName: "Build gmock"
  - script: sudo -E ./scripts/build_toolchain -s build_lcov
    displayName: "Build lcov"
  - script: sudo -E ./scripts/build_toolchain -s build_ncurses
    displayName: "Build ncurses"
  - script: sudo -E ./scripts/build_toolchain -s tree_cmd
    displayName: "Build tree_cmd"
  - script: make -j
    displayName: Build the kernel
  - script: make -j gtests
    displayName: Build the unit tests
  - script: ./build/gtests
    displayName: Run the unit tests
  - script: ./tests/runners/ci_run_all_tests_wrapper -c
    displayName: Run the system tests
