version: 2
jobs:

  debug_build:
    docker:
      - image: vvaltchev/tilck_build:latest
    environment:
      - RELEASE: 0
      - CMAKE_ARGS:
      - GTEST_SHUFFLE: 0
      - KERNEL_GCOV: 1
      - TEST_GCOV: 1
      - DUMP_COV: 1
      - REPORT_COV: 1
      - CODE_COV: 1
    steps:
      - checkout
      - run: mv /tilck_toolchain ./toolchain
      - run: make -j
      - run: make -j gtests
      - run: ./build/gtests
      - run: ./build/scripts/generate_test_coverage_report --codecov
      - run: ./build/st/run_all_tests

  release_build:
    docker:
      - image: vvaltchev/tilck_build:latest
    environment:
      - RELEASE: 1
      - CMAKE_ARGS:
      - GTEST_SHUFFLE: 0
    steps:
      - checkout
      - run: mv /tilck_toolchain ./toolchain
      - run: make -j
      - run: make -j gtests
      - run: ./build/st/run_all_tests

  debug_arch_gtests_build:
    docker:
      - image: vvaltchev/tilck_build:latest
    environment:
      - RELEASE: 0
      - CMAKE_ARGS: -DARCH_GTESTS=1
      - GTEST_SHUFFLE: 0
    steps:
      - checkout
      - run: mv /tilck_toolchain ./toolchain
      - run: make -j gtests
      - run: ./build/gtests

  debug_syscc_build:
    docker:
      - image: vvaltchev/tilck_build:latest
    environment:
      - RELEASE: 0
      - CMAKE_ARGS:
      - USE_SYSCC: 1
      - CC: gcc
      - CXX: g++
      - GTEST_SHUFFLE: 0
    steps:
      - checkout
      - run: mv /tilck_toolchain ./toolchain
      - run: ./scripts/build_toolchain -s build_libmusl
      - run: make -j
      - run: make -j gtests
      - run: ./build/st/run_all_tests

  debug_clang_build:
    docker:
      - image: vvaltchev/tilck_build:latest
    environment:
      - RELEASE: 0
      - CMAKE_ARGS: -DKERNEL_USE_SYSTEM_CC=1
      - CC: clang
      - CXX: clang++
      - GTEST_SHUFFLE: 0
    steps:
      - checkout
      - run: mv /tilck_toolchain ./toolchain
      - run: make -j
      - run: make -j gtests
      - run: ./build/gtests
      - run: ./build/st/run_all_tests

workflows:
  version: 2
  debug:
    jobs:
      - debug_build
  release:
    jobs:
      - release_build
  arch_gtests:
    jobs:
      - debug_arch_gtests_build
  syscc:
    jobs:
      - debug_syscc_build
  clang:
    jobs:
      - debug_clang_build
