version: 2
jobs:

  debug_build:
    docker:
      - image: vvaltchev/tilck_build:latest
    environment:
      - RELEASE: 0
      - CMAKE_ARGS: -DTEST_GCOV=on
      - GTEST_SHUFFLE: 0
    steps:
      - checkout
      - run: mv /tilck_toolchain ./toolchain
      - run: make -j
      - run: make -j gtests
      - run: ./build/st/run_all_tests

  debug_arch_gtests_build:
    docker:
      - image: vvaltchev/tilck_build:latest
    environment:
      - RELEASE: 0
      - CMAKE_ARGS: -DARCH_GTESTS=on
      - GTEST_SHUFFLE: 0
    steps:
      - checkout
      - run: mv /tilck_toolchain ./toolchain
      - run: make -j gtests
      - run: ./build/gtests

  release_build:
    docker:
      - image: vvaltchev/tilck_build:latest
    environment:
      - RELEASE: 1
      - CMAKE_ARGS:
      - GTEST_SHUFFLE: 0
    steps:
      - checkout
      - run: mv /tilck_toolchain ./toolchain
      - run: make -j
      - run: make -j gtests
      - run: ./build/st/run_all_tests

workflows:
  version: 2
  debug:
    jobs:
      - debug_build
  release:
    jobs:
      - release_build
  arch_gtests:
    jobs:
      - debug_arch_gtests_build

